# Generated by Django 3.2.7 on 2021-10-03 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf', '0002_alter_profile_phone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['-date_added']},
        ),
        migrations.AddField(
            model_name='profile',
            name='date_added',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
